### ISSUE TITLE
cambiar a angularVelocity

### ISSUE THREAD

**Issue by mcamp** [Grupo6-duckietown/DUI#4]
https://github.com/Grupo6-duckietown/DUI/blob/f9d53a13ebbfad431a631b288ce4d0a14655d1bc/DuckieGUI.py#L51

cambiar AngularVelocity a angularVelocity

**Comment by GiovaBe1901** [comment]
https://github.com/Grupo6-duckietown/DUI/blob/283efc9779b984678f96dc44cb64b842698ccd17/lib/speed_chooser.py#L71
